import { InventoryItem } from "./InventoryTable";

export const mockInventoryData: InventoryItem[] = [
  {
    id_item: 1001,
    codigo_item: "MT-2024-001",
    descricao_item: "Resistor 10K Ohm 1/4W",
    categoria: "Componentes Eletrônicos",
    unidade_medida: "UN",
    estoque_atual: 250,
    estoque_minimo: 500,
    estoque_maximo: 2000,
    consumo_medio_mensal: 450,
    consumo_ultimo_mes: 520,
    consumo_tendencia: "alta",
    cobertura_em_dias: 16,
    previsao_reposicao: "2025-11-01",
    quantidade_ideal_compra: 1000,
    status_critico: "critico",
    localizacao_estoque: "A-12-3",
    em_transito: 500,
    reservado: 150,
    data_ultima_compra: "2025-09-15",
    preco_medio_unitario: 0.15,
    fornecedor_principal: "TechParts Ltda",
    item_pai: "KIT-001",
    item_filho: undefined,
    observacoes: "Urgente: Estoque crítico, pedido em trânsito"
  },
  {
    id_item: 1002,
    codigo_item: "MT-2024-002",
    descricao_item: "Capacitor Eletrolítico 100uF 25V",
    categoria: "Componentes Eletrônicos",
    unidade_medida: "UN",
    estoque_atual: 1800,
    estoque_minimo: 800,
    estoque_maximo: 3000,
    consumo_medio_mensal: 600,
    consumo_ultimo_mes: 580,
    consumo_tendencia: "estavel",
    cobertura_em_dias: 90,
    previsao_reposicao: "2026-01-10",
    quantidade_ideal_compra: 800,
    status_critico: "normal",
    localizacao_estoque: "A-12-5",
    em_transito: 0,
    reservado: 200,
    data_ultima_compra: "2025-08-20",
    preco_medio_unitario: 0.35,
    fornecedor_principal: "EletroSupply",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: undefined
  },
  {
    id_item: 1003,
    codigo_item: "MT-2024-003",
    descricao_item: "LED Vermelho 5mm",
    categoria: "Componentes Eletrônicos",
    unidade_medida: "UN",
    estoque_atual: 650,
    estoque_minimo: 500,
    estoque_maximo: 2500,
    consumo_medio_mensal: 400,
    consumo_ultimo_mes: 320,
    consumo_tendencia: "baixa",
    cobertura_em_dias: 48,
    previsao_reposicao: "2025-12-01",
    quantidade_ideal_compra: 1000,
    status_critico: "atencao",
    localizacao_estoque: "B-08-2",
    em_transito: 0,
    reservado: 100,
    data_ultima_compra: "2025-09-01",
    preco_medio_unitario: 0.25,
    fornecedor_principal: "LightComponents Inc",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: "Consumo em queda, avaliar demanda"
  },
  {
    id_item: 1004,
    codigo_item: "MQ-2024-010",
    descricao_item: "Placa de Circuito Impresso PCB 10x15cm",
    categoria: "Materiais Base",
    unidade_medida: "UN",
    estoque_atual: 3200,
    estoque_minimo: 1000,
    estoque_maximo: 4000,
    consumo_medio_mensal: 800,
    consumo_ultimo_mes: 750,
    consumo_tendencia: "estavel",
    cobertura_em_dias: 120,
    previsao_reposicao: "2026-02-10",
    quantidade_ideal_compra: 1000,
    status_critico: "excesso",
    localizacao_estoque: "C-05-1",
    em_transito: 0,
    reservado: 400,
    data_ultima_compra: "2025-07-15",
    preco_medio_unitario: 4.50,
    fornecedor_principal: "PCB Solutions",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: "Estoque excedente, considerar redução no próximo pedido"
  },
  {
    id_item: 1005,
    codigo_item: "FE-2024-025",
    descricao_item: "Parafuso M3x10mm Inox",
    categoria: "Ferragens",
    unidade_medida: "UN",
    estoque_atual: 4500,
    estoque_minimo: 3000,
    estoque_maximo: 8000,
    consumo_medio_mensal: 2500,
    consumo_ultimo_mes: 2800,
    consumo_tendencia: "alta",
    cobertura_em_dias: 54,
    previsao_reposicao: "2025-12-10",
    quantidade_ideal_compra: 3000,
    status_critico: "normal",
    localizacao_estoque: "D-15-8",
    em_transito: 2000,
    reservado: 800,
    data_ultima_compra: "2025-09-10",
    preco_medio_unitario: 0.08,
    fornecedor_principal: "Metais & Cia",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: undefined
  },
  {
    id_item: 1006,
    codigo_item: "CB-2024-033",
    descricao_item: "Cabo Flexível 0.5mm² Vermelho (metro)",
    categoria: "Cabos e Fios",
    unidade_medida: "M",
    estoque_atual: 280,
    estoque_minimo: 500,
    estoque_maximo: 2000,
    consumo_medio_mensal: 600,
    consumo_ultimo_mes: 650,
    consumo_tendencia: "alta",
    cobertura_em_dias: 14,
    previsao_reposicao: "2025-10-30",
    quantidade_ideal_compra: 1000,
    status_critico: "critico",
    localizacao_estoque: "E-03-4",
    em_transito: 1000,
    reservado: 100,
    data_ultima_compra: "2025-09-05",
    preco_medio_unitario: 1.20,
    fornecedor_principal: "FioMax Distribuidora",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: "Atenção: Estoque crítico para produção"
  },
  {
    id_item: 1007,
    codigo_item: "IC-2024-042",
    descricao_item: "Microcontrolador ATmega328P",
    categoria: "Circuitos Integrados",
    unidade_medida: "UN",
    estoque_atual: 420,
    estoque_minimo: 200,
    estoque_maximo: 1000,
    consumo_medio_mensal: 150,
    consumo_ultimo_mes: 140,
    consumo_tendencia: "estavel",
    cobertura_em_dias: 84,
    previsao_reposicao: "2026-01-08",
    quantidade_ideal_compra: 300,
    status_critico: "normal",
    localizacao_estoque: "A-20-1",
    em_transito: 0,
    reservado: 80,
    data_ultima_compra: "2025-08-12",
    preco_medio_unitario: 12.50,
    fornecedor_principal: "MicroChip Global",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: undefined
  },
  {
    id_item: 1008,
    codigo_item: "PL-2024-055",
    descricao_item: "Caixa Plástica 100x68x50mm",
    categoria: "Embalagens",
    unidade_medida: "UN",
    estoque_atual: 850,
    estoque_minimo: 600,
    estoque_maximo: 1500,
    consumo_medio_mensal: 400,
    consumo_ultimo_mes: 380,
    consumo_tendencia: "estavel",
    cobertura_em_dias: 63,
    previsao_reposicao: "2025-12-18",
    quantidade_ideal_compra: 500,
    status_critico: "normal",
    localizacao_estoque: "F-10-2",
    em_transito: 0,
    reservado: 150,
    data_ultima_compra: "2025-09-01",
    preco_medio_unitario: 3.80,
    fornecedor_principal: "PlastBox Ind",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: undefined
  },
  {
    id_item: 1009,
    codigo_item: "TR-2024-067",
    descricao_item: "Transformador 12V 2A",
    categoria: "Fontes e Energia",
    unidade_medida: "UN",
    estoque_atual: 180,
    estoque_minimo: 150,
    estoque_maximo: 500,
    consumo_medio_mensal: 120,
    consumo_ultimo_mes: 95,
    consumo_tendencia: "baixa",
    cobertura_em_dias: 45,
    previsao_reposicao: "2025-11-30",
    quantidade_ideal_compra: 200,
    status_critico: "atencao",
    localizacao_estoque: "B-18-6",
    em_transito: 150,
    reservado: 40,
    data_ultima_compra: "2025-08-25",
    preco_medio_unitario: 18.90,
    fornecedor_principal: "Energia Total SA",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: "Pedido em trânsito, chegada prevista 28/10"
  },
  {
    id_item: 1010,
    codigo_item: "CN-2024-078",
    descricao_item: "Conector DB9 Macho",
    categoria: "Conectores",
    unidade_medida: "UN",
    estoque_atual: 920,
    estoque_minimo: 300,
    estoque_maximo: 1200,
    consumo_medio_mensal: 200,
    consumo_ultimo_mes: 210,
    consumo_tendencia: "estavel",
    cobertura_em_dias: 138,
    previsao_reposicao: "2026-03-02",
    quantidade_ideal_compra: 300,
    status_critico: "normal",
    localizacao_estoque: "A-15-7",
    em_transito: 0,
    reservado: 50,
    data_ultima_compra: "2025-07-20",
    preco_medio_unitario: 2.40,
    fornecedor_principal: "ConnectPro",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: undefined
  },
  {
    id_item: 1011,
    codigo_item: "SM-2024-089",
    descricao_item: "Sensor de Temperatura DS18B20",
    categoria: "Sensores",
    unidade_medida: "UN",
    estoque_atual: 95,
    estoque_minimo: 100,
    estoque_maximo: 400,
    consumo_medio_mensal: 80,
    consumo_ultimo_mes: 110,
    consumo_tendencia: "alta",
    cobertura_em_dias: 28,
    previsao_reposicao: "2025-11-13",
    quantidade_ideal_compra: 200,
    status_critico: "atencao",
    localizacao_estoque: "B-22-3",
    em_transito: 200,
    reservado: 30,
    data_ultima_compra: "2025-09-08",
    preco_medio_unitario: 8.75,
    fornecedor_principal: "SensorTech Brasil",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: "Monitorar consumo - tendência de alta"
  },
  {
    id_item: 1012,
    codigo_item: "AD-2024-095",
    descricao_item: "Adesivo Térmico 1g",
    categoria: "Materiais Auxiliares",
    unidade_medida: "UN",
    estoque_atual: 340,
    estoque_minimo: 200,
    estoque_maximo: 600,
    consumo_medio_mensal: 180,
    consumo_ultimo_mes: 165,
    consumo_tendencia: "estavel",
    cobertura_em_dias: 56,
    previsao_reposicao: "2025-12-11",
    quantidade_ideal_compra: 200,
    status_critico: "normal",
    localizacao_estoque: "C-08-9",
    em_transito: 0,
    reservado: 60,
    data_ultima_compra: "2025-09-12",
    preco_medio_unitario: 3.20,
    fornecedor_principal: "ThermalPro",
    item_pai: undefined,
    item_filho: undefined,
    observacoes: undefined
  }
];
