// The file `c:\Users\jotaa\OneDrive\Documentos\Vscode\Nexum\Nexum-FrontEnd2\src\components\mockSupplierData.ts` exists, but is empty
export const mockSupplierData = [
	{
		id: 1,
		nome: "TechParts Ltda",
		cnpj: "12.345.678/0001-90",
		categoria: "Componentes Eletrônicos",
		status: "Ativo",
		cidade: "São Paulo",
		estado: "SP",
		email: "contato@techparts.com",
		telefone: "(11) 4000-0000",
		avaliacao: 4.5,
	},
	{
		id: 2,
		nome: "EletroSupply",
		cnpj: "98.765.432/0001-11",
		categoria: "Fontes e Energia",
		status: "Ativo",
		cidade: "Campinas",
		estado: "SP",
		email: "vendas@eletrosupply.com",
		telefone: "(19) 3000-1111",
		avaliacao: 4.0,
	},
	{
		id: 3,
		nome: "Ferragens Brasil",
		cnpj: "22.333.444/0001-55",
		categoria: "Ferragens",
		status: "Inativo",
		cidade: "Belo Horizonte",
		estado: "MG",
		email: "contato@ferragensbr.com",
		telefone: "(31) 3333-4444",
		avaliacao: 3.8,
	},
];
